
// =========================================================
// DATOS: CATÁLOGO DE PRODUCTOS
// =========================================================
// Arreglo base de "Medicamentos y Vacunas" de la clínica. Es la fuente desde
// la que se listan los productos; el administrador lo modifica y los cambios
// se guardan en localStorage (ver nucleo/catalogo.js).
// En React: este archivo pasa a ser un módulo de datos (o la respuesta de la API).

const CATEGORIAS_PRODUCTO = [
  "Antibióticos",
  "Antiparasitarios",
  "Antiinflamatorios",
  "Dermatología",
  "Digestivo",
  "Cardíaco",
  "Analgésicos",
  "Vacunas",
  "Suplementos",
];

const IMAGEN_POR_DEFECTO = "../img/logo.svg";

const PRODUCTOS_BASE = [
  {
    id: "ME001",
    name: "Amoxibay 250mg",
    description: "Amoxicilina — Blíster 10 comp.",
    species: "Perro / Gato",
    price: 4200,
    stock: 45,
    stockCritico: 20,
    category: "Antibióticos",
    image: "../img/Amoxibay.png",
  },
  {
    id: "ME002",
    name: "Enrox 50mg",
    description: "Enrofloxacino — Blíster 10 comp.",
    species: "Perro / Gato",
    price: 6800,
    stock: 30,
    stockCritico: 20,
    category: "Antibióticos",
    image: "../img/enrrox.jpg",
  },
  {
    id: "ME003",
    name: "Metrobay 250mg",
    description: "Metronidazol — Blíster 10 comp.",
    species: "Perro / Gato",
    price: 3900,
    stock: 28,
    stockCritico: 20,
    category: "Antibióticos",
    image: "../img/Metrobay.jpg",
  },
  {
    id: "ME004",
    name: "Nexgard",
    description: "Afoxolaner — Masticable 1 unid.",
    species: "Perro",
    price: 9500,
    stock: 60,
    stockCritico: 20,
    category: "Antiparasitarios",
    image: "../img/Nexgard.jpg",
  },
  {
    id: "ME005",
    name: "Bravecto",
    description: "Fluralaner — Masticable 1 unid.",
    species: "Perro",
    price: 18900,
    stock: 40,
    stockCritico: 20,
    category: "Antiparasitarios",
    image: "../img/Bravecto.jpg",
  },
  {
    id: "ME006",
    name: "Revolution Plus",
    description: "Selamectina + Sarolaner — Pipeta 1 unid.",
    species: "Gato",
    price: 14500,
    stock: 35,
    stockCritico: 20,
    category: "Antiparasitarios",
    image: "../img/RevolutionPlus.jpg",
  },
  {
    id: "ME007",
    name: "Drontal Plus",
    description: "Praziquantel + Pamoato — Comprimido 1 unid.",
    species: "Perro",
    price: 3200,
    stock: 80,
    stockCritico: 20,
    category: "Antiparasitarios",
    image: "../img/DrontalPlus.jpg",
  },
  {
    id: "ME008",
    name: "Milbemax Gato",
    description: "Milbemicina + Praziq. — Comprimido 2 unid.",
    species: "Gato",
    price: 6800,
    stock: 50,
    stockCritico: 20,
    category: "Antiparasitarios",
    image: "../img/MilbemaxGato.jpg",
  },
  {
    id: "ME009",
    name: "Meloxicam 1mg",
    description: "Meloxicam — Blíster 10 comp.",
    species: "Perro / Gato",
    price: 4500,
    stock: 55,
    stockCritico: 20,
    category: "Antiinflamatorios",
    image: "../img/Metrobay.jpg",
  },
  {
    id: "ME010",
    name: "Carprofen 50mg",
    description: "Carprofeno — Blíster 10 comp.",
    species: "Perro",
    price: 9800,
    stock: 30,
    stockCritico: 20,
    category: "Antiinflamatorios",
    image: "../img/apoquel.jpg",
  },
  {
    id: "ME011",
    name: "Clorhexidina shampoo",
    description: "Clorhexidina 2% — Frasco 250ml",
    species: "Perro / Gato",
    price: 8900,
    stock: 25,
    stockCritico: 20,
    category: "Dermatología",
    image: "../img/Omeprazol.jpg",
  },
  {
    id: "ME012",
    name: "Malaseb shampoo",
    description: "Miconazol + Clorhex. — Frasco 250ml",
    species: "Perro / Gato",
    price: 12500,
    stock: 20,
    stockCritico: 20,
    category: "Dermatología",
    image: "../img/Tramadol.jpg",
  },
  {
    id: "ME013",
    name: "Apoquel 16mg",
    description: "Oclacitinib — Blíster 10 comp.",
    species: "Perro",
    price: 22000,
    stock: 18,
    stockCritico: 20,
    category: "Dermatología",
    image: "../img/apoquel.jpg",
  },
  {
    id: "ME014",
    name: "Probifor",
    description: "Bacillus clausii — Sobre 5ml x10",
    species: "Perro / Gato",
    price: 5600,
    stock: 40,
    stockCritico: 20,
    category: "Digestivo",
    image: "../img/probifor.jpg",
  },
  {
    id: "ME015",
    name: "Omeprazol 10mg vet",
    description: "Omeprazol — Blíster 10 comp.",
    species: "Perro / Gato",
    price: 3800,
    stock: 35,
    stockCritico: 20,
    category: "Digestivo",
    image: "../img/Omeprazol.jpg",
  },
  {
    id: "ME016",
    name: "Vetmedin 2.5mg",
    description: "Pimobendan — Blíster 10 comp.",
    species: "Perro",
    price: 28000,
    stock: 15,
    stockCritico: 20,
    category: "Cardíaco",
    image: "../img/Vetmedin.jpg",
  },
  {
    id: "ME017",
    name: "Tramadol 50mg vet",
    description: "Tramadol — Blíster 10 comp.",
    species: "Perro",
    price: 5200,
    stock: 22,
    stockCritico: 20,
    category: "Analgésicos",
    image: "../img/Tramadol.jpg",
  },
  {
    id: "ME018",
    name: "Nobivac DHPPi",
    description: "Vacuna polivalente — Vial 1 dosis",
    species: "Perro",
    price: 8500,
    stock: 48,
    stockCritico: 20,
    category: "Vacunas",
    image: "../img/NobivacDHPPi.jpg",
  },
  {
    id: "ME019",
    name: "Nobivac Rabies",
    description: "Vacuna antirrábica — Vial 1 dosis",
    species: "Perro / Gato",
    price: 5800,
    stock: 60,
    stockCritico: 20,
    category: "Vacunas",
    image: "../img/NobivacRabies.jpg",
  },
  {
    id: "ME020",
    name: "Felocell CVR",
    description: "Vacuna triple felina — Vial 1 dosis",
    species: "Gato",
    price: 7200,
    stock: 36,
    stockCritico: 20,
    category: "Vacunas",
    image: "../img/FelocellCVR.jpg",
  },
  {
    id: "ME021",
    name: "Omega vet 3-6-9",
    description: "Ácidos grasos omega — Frasco 100ml",
    species: "Perro / Gato",
    price: 9900,
    stock: 30,
    stockCritico: 20,
    category: "Suplementos",
    image: "../img/Omegavet%203-6-9.jpg",
  },
  {
    id: "ME022",
    name: "Condrovet forte",
    description: "Condroitín + Glucos. — Blíster 30 comp.",
    species: "Perro",
    price: 14500,
    stock: 25,
    stockCritico: 20,
    category: "Suplementos",
    image: "../img/Condrovetforte.jpg",
  },
];

// =========================================================
// DATOS: REGIONES Y COMUNAS
// =========================================================
// Arreglo de regiones con sus comunas para los selects encadenados.

const REGIONES_COMUNAS = {
  "Arica y Parinacota": ["Arica", "Camarones", "Putre", "General Lagos"],
  Tarapacá: ["Iquique", "Alto Hospicio", "Pozo Almonte"],
  Antofagasta: ["Antofagasta", "Calama", "Tocopilla"],
  Atacama: ["Copiapó", "Vallenar", "Chañaral"],
  Coquimbo: ["La Serena", "Coquimbo", "Ovalle"],
  Valparaíso: ["Valparaíso", "Viña del Mar", "Quilpué"],
  "Metropolitana de Santiago": [
    "Santiago",
    "Providencia",
    "Las Condes",
    "Maipú",
    "Puente Alto",
    "Ñuñoa",
    "La Florida",
    "Peñalolén",
  ],
  "Libertador General Bernardo O'Higgins": [
    "Rancagua",
    "San Fernando",
    "Rengo",
  ],
  Maule: ["Talca", "Curicó", "Linares"],
  Ñuble: ["Chillán", "San Carlos", "Bulnes"],
  Biobío: ["Concepción", "Talcahuano", "Los Ángeles"],
  "La Araucanía": ["Temuco", "Villarrica", "Angol"],
  "Los Ríos": ["Valdivia", "La Unión"],
  "Los Lagos": ["Puerto Montt", "Osorno", "Castro"],
  Aysén: ["Coyhaique", "Puerto Aysén"],
  Magallanes: ["Punta Arenas", "Puerto Natales"],
};

// =========================================================
// DATOS: CUENTAS Y EQUIPO INICIALES
// =========================================================
// Cuentas de demostración (una por rol) y equipo que se muestra en el inicio.
// Se cargan en localStorage la primera vez (ver nucleo/semilla.js).

// Cuentas de demostración, una por cada rol del sistema.
const CUENTAS_INICIALES = [
  {
    run: "111111111",
    name: "Admin",
    apellido: "NutriDifs",
    email: "admin@duoc.cl",
    password: "Admin123",
    role: "Administrador",
  },
  {
    run: "222222222",
    name: "Vendedor",
    apellido: "NutriDifs",
    email: "vendedor@duoc.cl",
    password: "Vende123",
    role: "Vendedor",
  },
  {
    run: "333333333",
    name: "Cliente",
    apellido: "Demo",
    email: "cliente@gmail.com",
    password: "Cliente1",
    role: "Cliente",
  },
];

// Integrantes que aparecen en la sección "El equipo" del inicio.
const EQUIPO_INICIAL = [
  {
    id: "USR001",
    name: "Carolina Quinan",
    email: "carolina@gmail.com",
    role: "Administrador",
    status: "Activo",
  },
  {
    id: "USR002",
    name: "Liza Micele",
    email: "liza@gmail.com",
    role: "Administrador",
    status: "Activo",
  },
];
